using System.Collections.Generic;
using System.Linq;
using GiGraph.Dot.Entities.Types.Labels;

namespace GiGraph.Dot.Entities.Types.Strings
{
    /// <summary>
    ///     Facilitates building text with escape sequences that format its lines or hold a place for identifiers filled in on graph
    ///     visualization. The output generated by the <see cref="ToFormattedText" /> method may be assigned the label attribute of an
    ///     element or any other <see cref="DotLabel" /> and <see cref="DotEscapeString" /> type attributes.
    /// </summary>
    public class DotTextFormatter
    {
        protected readonly List<DotEscapeString> _items = new();

        /// <summary>
        ///     Creates a new instance.
        /// </summary>
        public DotTextFormatter()
        {
        }

        /// <summary>
        ///     Creates a new instance initialized with text.
        /// </summary>
        /// <param name="text">
        ///     The text to initialize the instance with.
        /// </param>
        public DotTextFormatter(DotEscapeString text)
        {
            _items.Add(text);
        }

        /// <summary>
        ///     Appends the specified text to the instance.
        /// </summary>
        /// <param name="text">
        ///     The text to append to the instance.
        /// </param>
        public virtual DotTextFormatter Append(DotEscapeString text)
        {
            _items.Add(text);
            return this;
        }

        /// <summary>
        ///     Appends the specified escaped text to the instance (the text will not be processed further, so it should follow the escaping
        ///     rules available in the
        ///     <see href="http://www.graphviz.org/doc/info/attrs.html#k:escString">
        ///         documentation
        ///     </see>
        ///     ).
        /// </summary>
        /// <param name="escapedText">
        ///     The escaped text to append to the instance.
        /// </param>
        public virtual DotTextFormatter AppendEscaped(string escapedText)
        {
            _items.Add((DotEscapedString) escapedText);
            return this;
        }

        /// <summary>
        ///     Appends a line break to the instance.
        /// </summary>
        public virtual DotTextFormatter AppendLine()
        {
            _items.Add(DotEscapeString.LineBreak);
            return this;
        }

        /// <summary>
        ///     Appends the specified line of text to the instance.
        /// </summary>
        /// <param name="line">
        ///     The line of text to append to the instance.
        /// </param>
        public virtual DotTextFormatter AppendLine(DotEscapeString line)
        {
            _items.Add(line);
            return AppendLine();
        }

        /// <summary>
        ///     Appends the specified line of escaped text to the instance (the text will not be processed further, so it should follow the
        ///     escaping rules available in the
        ///     <see href="http://www.graphviz.org/doc/info/attrs.html#k:escString">
        ///         documentation
        ///     </see>
        ///     ).
        /// </summary>
        /// <param name="escapedLine">
        ///     The escaped line of text to append to the instance.
        /// </param>
        public virtual DotTextFormatter AppendEscapedLine(string escapedLine)
        {
            return AppendLine((DotEscapedString) escapedLine);
        }

        /// <summary>
        ///     Appends the specified line of text to the instance and marks it as left-justified (if the text contains line breaks,
        ///     justification will be applied to the last line only on graph visualization).
        /// </summary>
        /// <param name="line">
        ///     The line of text to append to the instance.
        /// </param>
        public virtual DotTextFormatter AppendLineLeftJustified(DotEscapeString line)
        {
            return Append(line).JustifyLeft();
        }

        /// <summary>
        ///     Appends the specified line of escaped text to the instance and marks it as left-justified (if the text contains line breaks,
        ///     justification will be applied to the last line only on graph visualization).
        /// </summary>
        /// <param name="line">
        ///     The line of text to append to the instance.
        /// </param>
        public virtual DotTextFormatter AppendEscapedLineLeftJustified(string line)
        {
            return AppendEscaped(line).JustifyLeft();
        }

        /// <summary>
        ///     Appends the specified line of text to the instance and marks it as right-justified (if the text contains line breaks,
        ///     justification will be applied to the last line only on graph visualization).
        /// </summary>
        /// <param name="line">
        ///     The line of text to append to the instance.
        /// </param>
        public virtual DotTextFormatter AppendLineRightJustified(DotEscapeString line)
        {
            return Append(line).JustifyRight();
        }

        /// <summary>
        ///     Appends the specified line of escaped text to the instance and marks it as right-justified (if the text contains line breaks,
        ///     justification will be applied to the last line only on graph visualization).
        /// </summary>
        /// <param name="line">
        ///     The line of text to append to the instance.
        /// </param>
        public virtual DotTextFormatter AppendEscapedLineRightJustified(string line)
        {
            return AppendEscaped(line).JustifyRight();
        }

        /// <summary>
        ///     <para>
        ///         Causes the last line of the previously added text to be left-justified.
        ///     </para>
        ///     <para>
        ///         Note that if further text is added to the instance after the method is called, it will appear in a new line.
        ///     </para>
        /// </summary>
        public virtual DotTextFormatter JustifyLeft()
        {
            return Append(DotEscapeString.LeftJustification);
        }

        /// <summary>
        ///     <para>
        ///         Causes the last line of the previously added text to be right-justified.
        ///     </para>
        ///     <para>
        ///         Note that if further text is added to the instance after the method is called, it will appear in a new line.
        ///     </para>
        /// </summary>
        public virtual DotTextFormatter JustifyRight()
        {
            return Append(DotEscapeString.RightJustification);
        }

        /// <summary>
        ///     Appends a placeholder replaced with the label of the current object when the graph is visualized.
        /// </summary>
        public virtual DotTextFormatter AppendLabel()
        {
            return Append(DotEscapeString.Label);
        }

        /// <summary>
        ///     Appends a placeholder replaced with the identifier of the graph when the graph is visualized.
        /// </summary>
        public virtual DotTextFormatter AppendGraphId()
        {
            return Append(DotEscapeString.GraphId);
        }

        /// <summary>
        ///     Appends a placeholder replaced with the definition of the current edge when the graph is visualized. Applicable to edges
        ///     only.
        /// </summary>
        public virtual DotTextFormatter AppendEdgeDefinition()
        {
            return Append(DotEscapeString.EdgeDefinition);
        }

        /// <summary>
        ///     Appends a placeholder replaced with the identifier of the tail node of the current edge when the graph is visualized.
        ///     Applicable to edges only.
        /// </summary>
        public virtual DotTextFormatter AppendEdgeTailNodeId()
        {
            return Append(DotEscapeString.EdgeTailNodeId);
        }

        /// <summary>
        ///     Appends a placeholder replaced with the identifier of the head node of the current edge when the graph is visualized.
        ///     Applicable to edges only.
        /// </summary>
        public virtual DotTextFormatter AppendEdgeHeadNodeId()
        {
            return Append(DotEscapeString.EdgeHeadNodeId);
        }

        /// <summary>
        ///     Appends a placeholder replaced with the identifier of the current node when the graph is visualized. Applicable to nodes
        ///     only.
        /// </summary>
        public virtual DotTextFormatter AppendNodeId()
        {
            return Append(DotEscapeString.NodeId);
        }

        /// <summary>
        ///     Returns content as a concatenated string.
        /// </summary>
        public override string ToString()
        {
            return string.Join(string.Empty, _items.Select(item => item?.ToString()));
        }

        /// <summary>
        ///     Returns content as formatted text that can be used as a label of an element.
        /// </summary>
        public virtual DotEscapeString ToFormattedText()
        {
            return new DotConcatenatedEscapeString(_items.ToArray());
        }
    }
}