name: Publish a NuGet Package

on:
  release:
    types: [ published ]

env:
  BRANCH: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore

      - shell: pwsh
        name: Create SNK File
        env:
          SNK: ${{ secrets.snk }}
        run: |
          $snk = [Convert]::FromBase64String("$env:SNK")
          Set-Content "src\GiGraph.Dot\GiGraph.snk" -Value $snk -AsByteStream

      - name: Build NuGet Package
        run: dotnet pack src\GiGraph.Dot\GiGraph.Dot.csproj --configuration Publish -p:Repository=${{ github.repository }} -p:Branch=${{ env.BRANCH }} -p:Commit=${{ github.sha }}

      - name: Publish NuGet Package
        run: dotnet nuget push src\GiGraph.Dot\bin\Publish\GiGraph.Dot.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_api_key }}